DOMAIN = 'localhost:8000'
ADMIN_UN = 'jack'
ADMIN_UE = 'jackdreilly@gmail.com'
ADMIN_PW = 'jack1234'
DB_ENGINE = 'sqlite3' # mysql
DB_NAME = 'Expenses.db'
DB_USER = ''
DB_PASSWORD = ''
DB_HOST = '' # localhost
DB_PORT = '' # 3306
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'jackdreilly@gmail.com'
EMAIL_HOST_PASSWORD = 'jefedeseguridad'
EMAIL_USE_TLS = True